_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 12 #base classes
DATASETS:
  TEST: ('custom_test_all_aop',)
SOLVER:
  BASE_LR: 0.02
  IMS_PER_BATCH: 2
  STEPS: (1500, 3000)
  MAX_ITER: 4000
OUTPUT_DIR: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_baseline"
