name: wfsdet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cudatoolkit
  - pip
  - pip:
    - termcolor
    - cython
    - numpy
    - tqdm
    - matplotlib
    - termcolor
    - yacs
    - tabulate
    - cloudpickle
    - Pillow
    - imagesize
    - tensorboard
    - opencv-python
    - torch
    - torchvision
    - lvis
    - omegaconf>=2
    - iopath
    - git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
    - git+https://github.com/facebookresearch/fvcore.git
