name: wfsdet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - termcolor
    - numpy
    - tqdm
    - matplotlib
    - termcolor
    - yacs
    - tabulate
    - cloudpickle
    - Pillow
    - imagesize
    - tensorboard
    - opencv-python
    - torch
    - torchvision
    - lvis
    - omegaconf>=2
    - fvcore==0.1.4
    - iopath
