name: wfsdet
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - termcolor
    - numpy
    - tqdm
    - matplotlib
    - termcolor
    - yacs
    - tabulate
    - cloudpickle
    - Pillow
    - imagesize
    - tensorboard
    - opencv-python
    - torch
    - torchvision
    - lvis
